name: Cleanup

on: delete

defaults:
  run:
    working-directory: ./

jobs:
  cleanup:
    name: Remove branch Lambda

    runs-on: ubuntu-latest

    env:
      PR_NUMBER: ${{ github.event.number }}

    steps:
      - uses: actions/checkout@v2

      - name: Get branch name (merge)
        if: github.event_name != 'pull_request'
        shell: bash
        run: echo "BRANCH_NAME=$(echo ${GITHUB_REF#refs/heads/} | tr / -)" >> $GITHUB_ENV

      - name: Get branch name (pull request)
        if: github.event_name == 'pull_request'
        shell: bash
        run: echo "BRANCH_NAME=$(echo ${GITHUB_HEAD_REF} | tr / -)" >> $GITHUB_ENV

      - name: Step that prints name of pull request number 111
        run: |
          echo "Pull request's base branch is: ${PR_NUMBER}"
