name: Cleanup alt1

on: delete

defaults:
  run:
    working-directory: ./

jobs:
  cleanup:
    name: Remove branch Lambda

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Get branch name (merge)
        if: github.event_name != 'pull_request'
        shell: bash
        run: echo "BRANCH_NAME=$(echo ${GITHUB_REF#refs/heads/} | tr / -)" >> $GITHUB_ENV

      - name: Get branch name (pull request)
        if: github.event_name == 'pull_request'
        shell: bash
        run: echo "BRANCH_NAME=$(echo ${GITHUB_HEAD_REF} | tr / -)" >> $GITHUB_ENV

      - name: echo dammit
        shell: bash
        run: echo "${BRANCH_NAME}"

      - name: another try
        shell: bash
        run: echo "${GITHUB_BASE_REF}"

      - name: Step that prints name of pull request's base branch
        run: |
          echo "Pull request's base branch is: ${BASE_BRANCH}"
        env:
          BASE_BRANCH: ${{ github.event.ref }}
